var COMMANDS  = { "en" : {
  "voice" : "UK English Female",
  "default" : 'Say "What can I say?" to see a list of commands...',
  "hi" : 'Hi, sexy!',
  "whois" : "Who are you?",
  "whatcanisay" : 'What can I say',
  "home" : 'Go home',
  "sleep" : 'Go to sleep',
  "wake" : 'Wake up',
  "debug" : 'Show debug information',
  "map" : 'Show map',
  "locaiton" : 'Show (me a) map of *location',
  "zoomin" : '(map) zoom in',
  "zoomout" : '(map) zoom out',
  "zoomvalue" : '(map) zoom (to) *value',
  "zoomreset" : '(map) reset zoom',
  "playyoutube" : 'play *term youtube',
  "ytbplaylist" : '*term playlist',
  "stopyoutube" : 'stop youtube',
  "subway" : 'show me *linenumber info at *station',
  "musicplay" : "play music",
  "musicstop" : "stop music",
  "info" :  "Here is a list of commands...",
  "news" : "Show me news"
},
  "ko" : {
    "voice" : "Korean Female",
    "default" : '원하는 명령을 말하세요',
    "whatcanisay" : '명령어 리스트',
    "whois" : "너는 누구니",
    "home" : '홈으로',
    "sleep" : '저리가',
    "wake" : '이리와',
    "debug" : '디버그',
    "map" : '지금 어디 야',
    "locaiton" : '*location위치 보여 줘',
    "zoomin" : '지도 확대',
    "zoomout" : '지도 축소',
    "zoomvalue" : '*value값으로지도 설정',
    "zoomreset" : '지도 리셋',
    "playyoutube" : '*term 동영상 (재생)(플레이)(보여 줘)',
    "ytbplaylist" : '*term 플레이어 (재생)(플레이)(보여 줘)',
    "stopyoutube" : '동영상 (중지)',
    "subway" : '*station역 *linenumber(호)선 *updown',
    "musicplay" : "음악 (재생)(켜 줘)",
    "musicstop" : "음악 (꺼 봐)(꺼 줘)(정지)(중지)(꺼져)",
    "info" : "이 중에서 명령어를 말하세요",
    "news" : "실시간뉴스"
  }
};
